package com.example.springbootdemo.product.model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.ID
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.SENDERID
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Long senderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.RECEIVERID
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Long receiverid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.TYPE
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.STATUS
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.GTM_CREATE
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Long gtmCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.QUESTIONID
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Long questionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFICATION
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Notification(Long id, Long senderid, Long receiverid, Integer type, Integer status, Long gtmCreate, Long questionid) {
        this.id = id;
        this.senderid = senderid;
        this.receiverid = receiverid;
        this.type = type;
        this.status = status;
        this.gtmCreate = gtmCreate;
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFICATION
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Notification() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.ID
     *
     * @return the value of NOTIFICATION.ID
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.ID
     *
     * @param id the value for NOTIFICATION.ID
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.SENDERID
     *
     * @return the value of NOTIFICATION.SENDERID
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Long getSenderid() {
        return senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.SENDERID
     *
     * @param senderid the value for NOTIFICATION.SENDERID
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setSenderid(Long senderid) {
        this.senderid = senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.RECEIVERID
     *
     * @return the value of NOTIFICATION.RECEIVERID
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Long getReceiverid() {
        return receiverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.RECEIVERID
     *
     * @param receiverid the value for NOTIFICATION.RECEIVERID
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setReceiverid(Long receiverid) {
        this.receiverid = receiverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.TYPE
     *
     * @return the value of NOTIFICATION.TYPE
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.TYPE
     *
     * @param type the value for NOTIFICATION.TYPE
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.STATUS
     *
     * @return the value of NOTIFICATION.STATUS
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.STATUS
     *
     * @param status the value for NOTIFICATION.STATUS
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.GTM_CREATE
     *
     * @return the value of NOTIFICATION.GTM_CREATE
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Long getGtmCreate() {
        return gtmCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.GTM_CREATE
     *
     * @param gtmCreate the value for NOTIFICATION.GTM_CREATE
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setGtmCreate(Long gtmCreate) {
        this.gtmCreate = gtmCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.QUESTIONID
     *
     * @return the value of NOTIFICATION.QUESTIONID
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Long getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.QUESTIONID
     *
     * @param questionid the value for NOTIFICATION.QUESTIONID
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setQuestionid(Long questionid) {
        this.questionid = questionid;
    }
}